apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-fastapi-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-fastapi-project
  template:
    metadata:
      labels:
        app: k8s-fastapi-project
    spec:
      containers:
      - name: k8s-fastapi-project
        image: rushabht/k8s-fastapi-project:latest
        ports:
        - containerPort: 8000
