apiVersion: v1
kind: Service
metadata:
  name: k8s-fastapi-project-service
spec:
  selector:
    app: k8s-fastapi-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
