apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # required field for kubernetes.io/basic-auth
  mongo-password: bW9uZ291cGFzc3dvcmQ= # required field for kubernetes.io/basic-auth